- hosts: all
  user: vagrant
  sudo: true
 
  tasks:
    - name: Install MySQL
      action: apt pkg={{item}} state=installed
      with_items:
        - mysql-server-core-5.5
        - mysql-client-core-5.5
        - libmysqlclient-dev
        - python-mysqldb
        - mysql-server
        - mysql-client